places = [
    {
        title:"Barrowland Ballroom",
        id:"1",
        location:"244 Gallowgate, Glasgow",
        price: "cash only",
        description: "The Barrowland Ballroom, affectionately known as 'The Barras,' was established in 1934, it has become a cornerstone of Glasgow's vibrant music scene, renowned for its excellent acoustics and distinctive sprung dance floor. The venue boasts a capacity of approximately 1,900 and has hosted legendary performances by artists such as David Bowie, U2, and Oasis. ",
        smallDescription: "The Barrowland Ballroom, affectionately known as 'The Barras,' is an iconic music venue...",
        image: "",
        type:"venue",
        phone: "+44 141 552 4601",
        email: "office@barrowland.co.uk",
        tips: {
            tip1title: "By Train",
            tip1: "The nearest train station is High Street (Glasgow), a 10-minute walk from the venue.",
            tip2title: "By Bus",
            tip2: "Several bus routes, including lines 2, 60, 60A, and sixty-one, have stops near the venue. The Ross Street stop is just a 2-minute walk away.",
            tip3title: "By Subway",
            tip3: "St Enoch SPT Subway Station is about a 17-minute walk from the venue.",
        },
        details: "For those driving, there is limited on-street parking available in the vicinity but be mindful of local parking restrictions. Given the venue's central location, utilizing public transport is often the most convenient option. "
    },
    {
        title:"The OVO Hydro",
        location:"Exhibition Way, Glasgow",
        price: "varies",
        description: "The OVO Hydro, located within Glasgow's Scottish Event Campus (SEC) at Exhibition Way, Glasgow, G3 8YW, is a premier entertainment venue renowned for hosting a diverse array of concerts, sporting events, and conferences. Designed by Foster + Partners, the arena boasts a distinctive amphitheatre design and a seating capacity of up to 14,300, making it a central hub for live entertainment in Scotland. ",
        smallDescription: "The OVO Hydro, located within Glasgow's Scottish Event Campus (SEC) at Exhibition Way...",
        image: "",
        type:"venue",
        phone: "+44 141 248 3000",
        email: "info@sec.co.uk",
        tips: {
            tip1title: "By Train",
            tip1: "The venue has a dedicated railway station, Exhibition Centre, with regular services from Glasgow Central Station's low-level platforms. Upon arrival, a covered walkway leads directly to the SEC complex. ",
            tip2title: "By Car",
            tip2: "For drivers, the SEC is conveniently located just off the M8 motorway. The main parking facility is the multi-storey car park on Stobcross Road (G3 8GS), which operates 24 hours and includes designated blue badge parking bays. ",
            tip3title: "Drop-off/Pick-up",
            tip3: "A designated drop-off and pick-up zone is situated at the west of the SEC Centre, offering a safe and convenient area for attendees. ",
        },
        details: "Given the venue's popularity, especially during major events, it is advisable to plan your journey in advance and consider using public transportation to avoid potential traffic congestion."
    },
    {
        title:"The Garage",
        location:"244 Gallowgate, Glasgow",
        price: "£4 - £8",
        description: "The Garage, located at 490 Sauchiehall Street, Glasgow, G2 3LW, is Scotland's largest nightclub and a renowned live music venue. Established in 1994, it features multiple rooms across four levels, each offering distinct musical genres to cater to diverse tastes. The Main Hall plays chart hits and remixes, G2 focuses on R&B, Desperados Bar offers nostalgic tunes, and The Attic showcases indie and rock music. Over the years, The Garage has hosted performances by notable artists such as Prince, Biffy Clyro, and One Direction.  ",
        smallDescription: "The Garage is Scotland's largest nightclub and a renowned live music venue. ",
        image: "",
        type:"venue",
        phone: "0141 332 1120",
        email: "garageall@hfents.com",
        tips: {
            tip1title: "By Train",
            tip1: "Charing Cross Station is a short walk away, providing convenient access for those traveling by train.",
            tip2title: "By Bus",
            tip2: "Multiple bus routes service Sauchiehall Street, with stops near the venue.",
            tip3title: "By Subway",
            tip3: "The nearest subway station is Cowcaddens, a 10-minute walk from the venue.",
        },
        details: "For those driving, be aware that parking in the area can be limited. It is advisable to use public transportation or nearby parking facilities. Additionally, The Garage offers limited wheelchair accessibility via the rear entrance on Renfrew Street. Patrons requiring assistance are encouraged to contact the venue in advance to arrange accommodations."
    },
    {
        title:"The O2 Academy Glasgow",
        location:"121 Eglinton Street, Glasgow",
        price: "cash only",
        description: "The O2 Academy Glasgow, located at 121 Eglinton Street, Glasgow, G5 9NT, is a renowned live music venue celebrated for its Art Deco architecture and vibrant event lineup. Since its opening in 2003, following a significant refurbishment of the former New Bedford Cinema, it has hosted a diverse array of concerts, club nights, and comedy shows. ",
        smallDescription: "The O2 Academy Glasgow is a renowned live music venue celebrated celebrated for its Art Deco...",
        image: "",
        type:"venue",
        phone: "0141 418 3000",
        email: "mail@o2academyglasgow.co.uk",
        tips: {
            tip1title: "By Train",
            tip1: "Glasgow Central Station is a 10-minute walk away, offering connections across Scotland and to various locations in England. ",
            tip2title: "By Bus",
            tip2: "Several bus routes service the area, with stops on Eglinton Street near the venue. ",
            tip3title: "By Subway",
            tip3: "The nearest subway station is Bridge Street, located about 300 meters from the venue on Eglinton Street. ",
        },
        details: `While there is no dedicated parking at the venue, on-street parking is available in the surrounding area, subject to local restrictions. Additionally, the Bridge Street subway station offers a 159-space car park approximately 300 meters away. For those requiring accessible facilities, the O2 Academy Glasgow provides a viewing platform, accessible toilets, and assistance for patrons with disabilities. It's recommended to contact the venue in advance to arrange any specific accommodations.` <br> `For the latest event listings, ticket purchases, and additional information, please visit the official website or reach out directly via phone or email.`
    },
    {
        title:"The Cathouse Rock Club",
        location:"15 Union Street, Glasgow",
        price: "cash only",
        description: "The Cathouse Rock Club, located at 15 Union Street, Glasgow, G1 3RB, is Scotland's premier rock venue since 1990. Known for its energetic atmosphere and diverse music selection, the club spans multiple levels, each offering distinct genres from classic rock and metal to alternative beats. Over the years, it has hosted performances by notable bands such as Anthrax, Pearl Jam, and Queens of the Stone Age. ",
        smallDescription: "The Cathouse Rock Club is Scotland's premier rock venue since 1990...",
        image: "",
        type:"venue",
        phone: "0141 248 6606",
        email: "cathouseall@hfents.com",
        tips: {
            tip1title: "By Train",
            tip1: "Glasgow Central Station is a short walk away, providing easy access for those traveling by train.",
            tip2title: "By Bus",
            tip2: "Numerous bus routes service Union Street and the surrounding area, making it convenient for bus travellers.",
            tip3title: "By Subway",
            tip3: "St Enoch Subway Station is a 5-minute walk from the venue.",
        },
        details: "For those driving, be aware that parking in the city centre can be limited and subject to restrictions. It's advisable to use public transportation or nearby parking facilities. The club operates enhanced security measures, including bag searches upon entry, to ensure patron safety. For the latest event listings, ticket purchases, and additional information, please visit the official website or contact the venue directly via phone or email. "
    }
]