places = [
    {
        title:"Barrowland Ballroom",
        id: '1',
        location:"244 Gallowgate, Glasgow",
        address:`<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2239.4355676680757!2d-4.239738822734608!3d55.8551089731223!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x488846a59bd6328b%3A0xb3c30647933bd008!2s244%20Gallowgate%2C%20Glasgow%20G4%200TT!5e0!3m2!1sen!2suk!4v1741211810596!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
        price: "cash only",
        description: "The Barrowland Ballroom, affectionately known as 'The Barras,' was established in 1934, it has become a cornerstone of Glasgow's vibrant music scene, renowned for its excellent acoustics and distinctive sprung dance floor. The venue boasts a capacity of approximately 1,900 and has hosted legendary performances by artists such as David Bowie, U2, and Oasis. ",
        smallDescription: "The Barrowland Ballroom, affectionately known as 'The Barras,' is an iconic music venue...",
        image: "",
        type:"venue",
        phone: "+44 141 552 4601",
        email: "office@barrowland.co.uk",
        tips: {
            tip1title: "By Train",
            tip1: "The nearest train station is High Street (Glasgow), a 10-minute walk from the venue.",
            tip2title: "By Bus",
            tip2: "Several bus routes, including lines 2, 60, 60A, and sixty-one, have stops near the venue. The Ross Street stop is just a 2-minute walk away.",
            tip3title: "By Subway",
            tip3: "St Enoch SPT Subway Station is about a 17-minute walk from the venue.",
        },
        details: "For those driving, there is limited on-street parking available in the vicinity but be mindful of local parking restrictions. Given the venue's central location, utilizing public transport is often the most convenient option. "
    },
    {
        title:"The OVO Hydro",
        id: '2',
        location:"Exhibition Way, Glasgow",
        address:`<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2239.1755435055234!2d-4.288161922734376!3d55.859620673124084!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4888467f6ad396bb%3A0x6bdf1ba31717c9d6!2sOVO%20Hydro!5e0!3m2!1sen!2suk!4v1741211925089!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
        price: "££",
        description: "The OVO Hydro, located within Glasgow's Scottish Event Campus (SEC) at Exhibition Way, Glasgow, G3 8YW, is a premier entertainment venue renowned for hosting a diverse array of concerts, sporting events, and conferences. Designed by Foster + Partners, the arena boasts a distinctive amphitheatre design and a seating capacity of up to 14,300, making it a central hub for live entertainment in Scotland. ",
        smallDescription: "The OVO Hydro, located within Glasgow's Scottish Event Campus (SEC) at Exhibition Way...",
        image: "",
        type:"venue",
        phone: "+44 141 248 3000",
        email: "info@sec.co.uk",
        tips: {
            tip1title: "By Train",
            tip1: "The venue has a dedicated railway station, Exhibition Centre, with regular services from Glasgow Central Station's low-level platforms. Upon arrival, a covered walkway leads directly to the SEC complex. ",
            tip2title: "By Car",
            tip2: "For drivers, the SEC is conveniently located just off the M8 motorway. The main parking facility is the multi-storey car park on Stobcross Road (G3 8GS), which operates 24 hours and includes designated blue badge parking bays. ",
            tip3title: "Drop-off/Pick-up",
            tip3: "A designated drop-off and pick-up zone is situated at the west of the SEC Centre, offering a safe and convenient area for attendees. ",
        },
        details: "Given the venue's popularity, especially during major events, it is advisable to plan your journey in advance and consider using public transportation to avoid potential traffic congestion."
    },
    {
        title:"The Garage",
        id: '3',
        location:"490 Sauchiehall Street, Glasgow",
        address:`<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d17910.36879790593!2d-4.306901125683534!3d55.86620400000004!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x488844248297fa53%3A0x35dbe1491a124a4e!2sThe%20Garage!5e0!3m2!1sen!2suk!4v1741211994533!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
        price: "£",
        description: "The Garage, located at 490 Sauchiehall Street, Glasgow, G2 3LW, is Scotland's largest nightclub and a renowned live music venue. Established in 1994, it features multiple rooms across four levels, each offering distinct musical genres to cater to diverse tastes. The Main Hall plays chart hits and remixes, G2 focuses on R&B, Desperados Bar offers nostalgic tunes, and The Attic showcases indie and rock music. Over the years, The Garage has hosted performances by notable artists such as Prince, Biffy Clyro, and One Direction.  ",
        smallDescription: "The Garage is Scotland's largest nightclub and a renowned live music venue. ",
        image: "",
        type:"venue",
        phone: "0141 332 1120",
        email: "garageall@hfents.com",
        tips: {
            tip1title: "By Train",
            tip1: "Charing Cross Station is a short walk away, providing convenient access for those traveling by train.",
            tip2title: "By Bus",
            tip2: "Multiple bus routes service Sauchiehall Street, with stops near the venue.",
            tip3title: "By Subway",
            tip3: "The nearest subway station is Cowcaddens, a 10-minute walk from the venue.",
        },
        details: "For those driving, be aware that parking in the area can be limited. It is advisable to use public transportation or nearby parking facilities. Additionally, The Garage offers limited wheelchair accessibility via the rear entrance on Renfrew Street. Patrons requiring assistance are encouraged to contact the venue in advance to arrange accommodations."
    },
    {
        title:"The O2 Academy Glasgow",
        id: '4',
        location:"121 Eglinton Street, Glasgow",
        address:`<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1983.8033044072326!2d-4.261919057501498!3d55.8515078208848!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48884690a7786147%3A0xf5855cd8f822d132!2sO2%20Academy%20Glasgow!5e0!3m2!1sen!2suk!4v1741212044285!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
        price: "cash only",
        description: "The O2 Academy Glasgow, located at 121 Eglinton Street, Glasgow, G5 9NT, is a renowned live music venue celebrated for its Art Deco architecture and vibrant event lineup. Since its opening in 2003, following a significant refurbishment of the former New Bedford Cinema, it has hosted a diverse array of concerts, club nights, and comedy shows. ",
        smallDescription: "The O2 Academy Glasgow is a renowned live music venue celebrated celebrated for its Art Deco...",
        image: "",
        type:"venue",
        phone: "0141 418 3000",
        email: "mail@o2academyglasgow.co.uk",
        tips: {
            tip1title: "By Train",
            tip1: "Glasgow Central Station is a 10-minute walk away, offering connections across Scotland and to various locations in England. ",
            tip2title: "By Bus",
            tip2: "Several bus routes service the area, with stops on Eglinton Street near the venue. ",
            tip3title: "By Subway",
            tip3: "The nearest subway station is Bridge Street, located about 300 meters from the venue on Eglinton Street. ",
        },
        details: `While there is no dedicated parking at the venue, on-street parking is available in the surrounding area, subject to local restrictions. Additionally, the Bridge Street subway station offers a 159-space car park approximately 300 meters away. For those requiring accessible facilities, the O2 Academy Glasgow provides a viewing platform, accessible toilets, and assistance for patrons with disabilities. It's recommended to contact the venue in advance to arrange any specific accommodations. For the latest event listings, ticket purchases, and additional information, please visit the official website or reach out directly via phone or email.`
    },
    {
        title:"The Cathouse Rock Club",
        id: '5',
        location:"15 Union Street, Glasgow",
        address:`<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d559.8056573723738!2d-4.257650930293604!3d55.8588036983202!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4888469e93694b09%3A0xf6f9f1a254d72b45!2sCathouse%20Rock%20Club!5e0!3m2!1sen!2suk!4v1741212115729!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
        price: "cash only",
        description: "The Cathouse Rock Club, located at 15 Union Street, Glasgow, G1 3RB, is Scotland's premier rock venue since 1990. Known for its energetic atmosphere and diverse music selection, the club spans multiple levels, each offering distinct genres from classic rock and metal to alternative beats. Over the years, it has hosted performances by notable bands such as Anthrax, Pearl Jam, and Queens of the Stone Age. ",
        smallDescription: "The Cathouse Rock Club is Scotland's premier rock venue since 1990...",
        image: "",
        type:"venue",
        phone: "0141 248 6606",
        email: "cathouseall@hfents.com",
        tips: {
            tip1title: "By Train",
            tip1: "Glasgow Central Station is a short walk away, providing easy access for those traveling by train.",
            tip2title: "By Bus",
            tip2: "Numerous bus routes service Union Street and the surrounding area, making it convenient for bus travellers.",
            tip3title: "By Subway",
            tip3: "St Enoch Subway Station is a 5-minute walk from the venue.",
        },
        details: "For those driving, be aware that parking in the city centre can be limited and subject to restrictions. It's advisable to use public transportation or nearby parking facilities. The club operates enhanced security measures, including bag searches upon entry, to ensure patron safety. For the latest event listings, ticket purchases, and additional information, please visit the official website or contact the venue directly via phone or email. "
    },
    {
        title:"Kelvingrove Art Gallery and Museum",
        id: '6',
        location:"Argyle Street, Glasgow",
        address:`<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2238.658623782827!2d-4.2931788227338865!3d55.868589073127275!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x488845d16be594e9%3A0x5258b27cf1ca9ffe!2sKelvingrove%20Art%20Gallery%20and%20Museum!5e0!3m2!1sen!2suk!4v1741212149070!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
        price: "free",
        description: "Kelvingrove Art Gallery and Museum Is a popular museum situated on Argyle Street in Glasgow, Scotland (G3 8AG). Founded in 1901, it features more than 8,000 exhibits, including well-known paintings by Rembrandt, Monet, and Salvador Dalí, as well as displays on natural history, artefacts from ancient Egypt, and Scottish history. One of Scotland’s most visited cultural destinations, the museum is free to enter.",
        smallDescription: "Kelvingrove Art Gallery and Museum Is a popular museum situated on Argyle Street...",
        image: "",
        type:"museum",
        phone: "+44 141 276 9599",
        email: "museums@glasgowlife.org.uk",
        tips: {
            tip1title: "By Train",
            tip1: "The nearest train station is Partick Station, about a 20-minute walk away.",
            tip2title: "By Bus",
            tip2: "Several bus routes, including lines 2, 3, and 77, stop near the museum. The Kelvingrove Art Gallery stop is just a short walk away.",
            tip3title: "By Subway",
            tip3: "The nearest subway station is Kelvinhall, approximately a 10-minute walk from the museum.",
        },
        details: "Limited parking is available near the museum, including a pay-and-display car park on Bunhouse Road. However, using public transport is often the most convenient option due to the museum’s central location. "
    },
    {
        title:"Glasgow Science Centre",
        id: '7',
        location:"50 Pacific Quay, Glasgow",
        address:`<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1119.6153406412443!2d-4.2961468608472995!3d55.858663993280906!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x488846782dee2b5b%3A0xafd5499a54045124!2sGlasgow%20Science%20Centre!5e0!3m2!1sen!2suk!4v1741212209642!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
        price: "free",
        description: "Glasgow Science Centre is an interactive museum situated in Glasgow, Scotland’s G51 1EA, on the south bank of the Clyde River. It has an IMAX theatre, a modern planetarium, interactive exhibitions, and a 127-meter rotating tower with expansive city views. The center’s design aims to introduce science, technology, and innovation to guests of all ages. ",
        smallDescription: "Glasgow Science Centre is an interactive museum on the south bank of the Clyde River...",
        image: "",
        type:"museum",
        phone: "+44 141 420 5000 ",
        email: "contactus@glasgowsciencecentre.org",
        tips: {
            tip1title: "By Train",
            tip1: "The nearest train station is Exhibition Centre Station, about a 15-minute walk away.",
            tip2title: "By Bus",
            tip2: "Several bus routes, including lines 90, 23, and 26, stop near the centre",
            tip3title: "By Subway",
            tip3: "The nearest subway station is Cessnock, a 10-minute walk away.",
        },
        details: "For those driving,Paid parking is available at the centre’s dedicated car park"
    },
    {
        title:"People’s Palace",
        id: '8',
        location:"Glasgow Green, Glasgow",
        address:`<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2239.653439668686!2d-4.239655122734788!3d55.85132847312075!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x488846bac9de6045%3A0x68cbe249585ac38b!2sPeople&#39;s%20Palace!5e0!3m2!1sen!2suk!4v1741212247239!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
        price: "free",
        description: "People’s Palace is a museum dedicated to social history situated in Glasgow Green, Glasgow, Scotland, G40 1AT. It was first opened in 1898 and shows Glaswegians’ everyday lives and history from the 18th century to the present. The museum has interactive displays, personal artefacts, and photographs. The Winter Gardens, a stunning glasshouse with tropical plants, is attached to it. ",
        smallDescription: "Glasgow Science Centre is an interactive museum on the south bank of the Clyde River...",
        image: "",
        type:"museum",
        phone: "+44 141 276 0788",
        email: " museums@glasgowlife.org.uk",
        // tips: {
        //     tip1title: "By Train",
        //     tip1: "The nearest train station is Exhibition Centre Station, about a 15-minute walk away.",
        //     tip2title: "By Bus",
        //     tip2: "Several bus routes, including lines 90, 23, and 26, stop near the centre",
        //     tip3title: "By Subway",
        //     tip3: "The nearest subway station is Cessnock, a 10-minute walk away.",
        // },
        // details: "For those driving,Paid parking is available at the centre’s dedicated car park"
    },
    {
        title:"The Lighthouse",
        id: '9',
        location:"11 Mitchell Lane, Glasgow",
        address:`<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2239.157763125118!2d-4.257974522734333!3d55.85992917312404!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x488844211bbe84ff%3A0x486a362b13eb605f!2sThe%20Lighthouse!5e0!3m2!1sen!2suk!4v1741212353975!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
        price: "free",
        description: "The Lighthouse is located at 11 Mitchell Lane, Glasgow, G1 3NU, Scotland, and is the country’s Centre for Design and Architecture. Originally created by Charles Rennie Mackintosh in 1895 as the Glasgow Herald newspaper’s headquarters, it is now a centre for events, exhibitions, and innovative thinking. Explore Mackintosh’s creations, see exhibitions of modern design, and take in expansive views of Glasgow from the building’s tower.",
        smallDescription: "The Lighthouses the country’s Centre for Design and Architecture...",
        image: "",
        type:"museum",
        phone: "+44 141 276 5365",
        email: "info@thelighthouse.co.uk",
        tips: {
            tip1title: "By Train",
            tip1: "The nearest train stations are Glasgow Central and Glasgow Queen Street, both within a 5-minute walk. ",
            tip2title: "By Bus",
            tip2: "Numerous bus routes stop near Buchanan Street, just a short walk from the venue.",
            tip3title: "By Subway",
            tip3: "The nearest subway station is Buchanan Street, a 3-minute walk away.",
        },
        details: "For those driving, parking is available at nearby car parks, such as the NCP Mitchell Street Car Park, but using public transport is recommended due to the central location "
    },
    {
        title:"Ka Pao",
        id: '10',
        location:"26 Vinicombe Street, Glasgow",
        address:`<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2238.1627134049104!2d-4.292846622733438!3d55.87719207313054!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x488845c3b78d78bf%3A0x6e85f33566f0b16d!2sKa%20Pao%20Glasgow!5e0!3m2!1sen!2suk!4v1741212391775!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
        price: "£",
        description: "Colourful restaurant situated in Glasgow, Scotland, at 26 Vinicombe Street, G12 8BE. This Southeast Asian-inspired restaurant, housed in the historic Botanic Gardens Garage, serves a selection of small foods meant to be shared. It is a well-liked location for both informal dining and big events because of its vibrant and modern ambiance. ",
        smallDescription: "This Southeast Asian-inspired restaurant, housed in the historic Botanic Gardens Garage...",
        image: "",
        type:"restaurant",
        phone: "+44 141 483 6990",
        email: "glasgow@ka-pao.com",
        tips: {
            tip1title: "By Train",
            tip1: "The nearest train station is Hillhead, approximately a 5-minute walk from the restaurant. ",
            tip2title: "By Bus",
            tip2: "Several bus routes, including lines 6, 6A, and 8, have stops near Vinicombe Street",
            tip3title: "By Subway",
            tip3: "The Hillhead subway station is a short walk away, providing convenient access.",
        },
        details: "For those driving, limited street parking is available in the vicinity; however, utilizing public transport is recommended due to the central location. "
    },
    {
        title:"La Lanterna",
        id: '11',
        location:"35 Hope Street, Glasgow",
        address:`<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2239.1927301843148!2d-4.261887222734398!3d55.859322473123854!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4888469c2cf673b5%3A0x42ff43c3bb6c7618!2sLa%20Lanterna!5e0!3m2!1sen!2suk!4v1741212417908!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
        price: "££",
        description: "The oldest Italian restaurant in Glasgow, run by a family, is situated at 35 Hope Street, Glasgow, G2 6AE, Scotland. It was founded in 1970 and serves real Italian food, with a menu that includes classic dishes made with ingredients that are obtained locally and freshly. It is a favourite among both locals and tourists because of its cosy and welcoming atmosphere. ",
        smallDescription: "The oldest Italian restaurant in Glasgow, run by a family was founded in 1970 and serves real Italian food...",
        image: "",
        type:"restaurant",
        phone: "+44 141 221 9160",
        email: "lalanterna@btconnect.com",
        tips: {
            tip1title: "By Train",
            tip1: "The restaurant is a 2-minute walk from Glasgow Central Station, making it ideal for those arriving by train. ",
            tip2title: "By Bus",
            tip2: "Numerous bus routes serve the area, with stops near Hope Street.",
            tip3title: "By Subway",
            tip3: "The St Enoch subway station is approximately a 5-minute walk away. ",
        },
        details: "For those driving, Street parking is available, but due to the central location, public transport is often more convenient."
    },
    {
        title:"Miller & Carter",
        id: '12',
        location:"27-29 St. Vincent Street, Glasgow",
        address:`<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d599.9489504834911!2d-4.254938317320435!3d55.86112403567835!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4888469fb7cf6435%3A0xb9966f819bed23e2!2sMiller%20%26%20Carter%20Glasgow!5e0!3m2!1sen!2suk!4v1741212464479!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
        price: "£££",
        description: "Famous steakhouse in Glasgow, Scotland, at 27–29 St. Vincent Street. The restaurant, which is well-known for its excellent steaks, provides a casual dining experience with a menu that emphasises premium cuts of meat along with a selection of sides, desserts, and drinks. For those who enjoy steak and want a substantial lunch in a chic atmosphere, this is the perfect place. ",
        smallDescription: "The restaurant, which is well-known for its excellent steaks...",
        image: "",
        type:"restaurant",
        phone: "+44 141 332 8133",
        email: " info@millerandcarter.co.uk",
        tips: {
            tip1title: "By Train",
            tip1: "The nearest train stations are Glasgow Central and Glasgow Queen Street, both about a 10-minute walk away. ",
            tip2title: "By Bus",
            tip2: "Several bus routes, including lines 2, 100, and 18, have stops near St. Vincent Street.",
            tip3title: "By Subway",
            tip3: "The nearest subway station is Buchanan Street, approximately a 7-minute walk from the restaurant. ",
        },
        details: "For those driving, there is limited parking available on St. Vincent Street, but public transport is recommended due to the central location "
    },
    {
        title:"OX & Finch ",
        id: '13',
        location:"920 Sauchiehall Street, Glasgow",
        address:`<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2238.8174911954147!2d-4.287236722734043!3d55.86583287312629!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x488845d492ffafff%3A0xe310d41b51a8457e!2sOx%20and%20Finch!5e0!3m2!1sen!2suk!4v1741212504410!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
        price: "£",
        description: "Located at 920 Sauchiehall Street, Glasgow, G3 7TF, Scotland, this restaurant is contemporary and lively. The restaurant is well-known for its inventive small plates that are influenced by flavours from around the world and provide a modern take on traditional fare. The menu emphasises locally sourced, fresh ingredients and is intended to be shared. For those looking for a distinctive eating experience in a chic, laid-back setting, OX & Finch has grown in popularity.",
        smallDescription: "The restaurant is well-known for its inventive small plates that...",
        image: "",
        type:"restaurant",
        phone: "+44 141 339 8627",
        email: "info@oxandfinch.com",
        tips: {
            tip1title: "By Train",
            tip1: "The nearest train station is Charing Cross, about a 5-minute walk away.",
            tip2title: "By Bus",
            tip2: "Several bus routes, including lines 2, 9, and 77, have stops near Sauchiehall Street.",
            tip3title: "By Subway",
            tip3: "The nearest subway station is St George's Cross, a 10-minute walk away.",
        },
        details: "For those driving, limited on-street parking is available, but due to the central location, public transport is often the most convenient option."
    },
    {
        title:"Glasgow Green",
        id: '14',
        location:"Greendyke Street, Glasgow",
        address:`<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2239.781317145544!2d-4.237890522734893!3d55.849109473119974!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x488846a37a817f3b%3A0x4822cab96021be31!2sGlasgow%20Green!5e0!3m2!1sen!2suk!4v1741212549770!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
        price: "free",
        description: "Established in the 15th century, is the city's oldest public park, spanning 136 acres east of the Saltmarket and within walking distance from the city center. The park hosts several notable landmarks, including the People's Palace, a museum dedicated to Glasgow's social history; the Doulton Fountain, the world's largest terracotta fountain; and the Nelson Monument, a 43.5-meter tall column honoring Admiral Lord Nelson. Additionally, the McLennan Arch serves as a prominent gateway into the park.",
        smallDescription: "Established in the 15th century, is the city's oldest public park...",
        image: "",
        type:"park",
        phone: "0141 287 5064",
        email: "info@glasgowlife.org.uk",
        tips: {
            tip1title: "By Train",
            tip1: "Argyle Street Station is approximately a 15-minute walk from the park",
            tip2title: "By Bus",
            tip2: "Numerous bus routes service the area, with stops along London Road and the Saltmarket, adjacent to the park.",
            tip3title: "By Subway",
            tip3: "The nearest subway station is St Enoch, about a 20-minute walk from Glasgow Green.",
        },
        details: "For those driving, limited on-street parking is available in the vicinity, but it's advisable to use public transportation due to potential restrictions. The park is open at all times, though specific facilities like the People's Palace may have varying hours; contacting them directly for current information is recommended."
    },
    {
        title:"Alexandra Park",
        id: '15',
        location:"Greendyke Street, Glasgow",
        address:`<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d17918.251342669086!2d-4.25591509800408!3d55.84910772590211!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x488843f2c11c0ba3%3A0x74d49bb1c9f0a91c!2sAlexandra%20Park!5e0!3m2!1sen!2suk!4v1741212578260!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
        price: "free",
        description: "Alexandra Park, located in Glasgow's East End, spans 42 hectares (102 acres) and offers a variety of recreational facilities. Established in 1870 and named after Princess Alexandra of Denmark, the park provides panoramic views of Ben Lomond to the north and the Tinto Hills to the south from its highest point. Visitors can enjoy amenities such as bowling greens, a nine-hole golf course, two children's play areas, a mountain bike course, and a small picnic area. A notable feature within the park is the Saracen Fountain, a 40-foot cast-iron structure gifted to Glasgow after the 1901 International Exhibition.",
        smallDescription: "Alexandra Park, located in Glasgow's East End, spans...",
        image: "",
        type:"park",
        phone: "0141 276 0600",
        email: "info@glasgowlife.org.uk",
        tips: {
            tip1title: "By Train",
            tip1: "Alexandra Parade Station is adjacent to the park, providing convenient access.",
            tip2title: "By Bus",
            tip2: "Multiple bus routes service the area, with stops along Alexandra Parade and Cumbernauld Road, both bordering the park.",
            tip3title: "By Car",
            tip3: "Limited on-street parking is available near the park entrances; however, using public transport is advisable due to potential parking constraints.",
        },
        details: "The park is open daily from dawn to dusk, though specific facilities may have varying operating hours. For the most current information on events and facility availability, it's recommended to contact the park directly or visit the official website."
    },
    {
        title:"Linn Park",
        id: '16',
        location:"Linn Park, Glasgow",
        address:`<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2242.33410031575!2d-4.260874922737318!3d55.804799973103485!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x488847056f30d109%3A0x37b2c32713b94d38!2sLinn%20Park!5e0!3m2!1sen!2suk!4v1741212603432!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
        price: "free",
        description: "Linn Park, encompassing 82 hectares (203 acres), is Glasgow's second-largest park, nestled in the city's southern region. Established in 1919, the park offers a rich tapestry of natural beauty and historical significance. Visitors can explore woodland and river walks along the White Cart Water, encounter the picturesque 'Halfpenny Bridge' (also known as the White Bridge), and discover the remnants of Cathcart Castle, a 15th-century structure. The park also features an 18-hole public golf course, an orienteering course, and two children's play areas. Nature enthusiasts will appreciate the park's diverse habitats, home to over sixty bird species and a variety of flora. ",
        smallDescription: "Linn Park, encompassing 82 hectares (203 acres), is Glasgow's...",
        image: "",
        type:"park",
        phone: "0141 287 5064",
        email: " info@glasgowlife.org.uk",
        tips: {
            tip1title: "By Train",
            tip1: "Muirend Station is the closest railway station, approximately a 10-minute walk from the park's western entrance.",
            tip2title: "By Bus",
            tip2: "Several bus routes service the area, with stops along Clarkston Road and Carmunnock Road, providing easy access to the park.",
            tip3title: "By Car",
            tip3: "Limited parking is available near the park entrances, particularly off Linnview Avenue. Visitors are advised to arrive early, especially on weekends, to secure a spot.",
        },
        details: "The park is open year-round, offering a serene escape from urban life. While the main pathways are well-maintained, some trails may be uneven or steep, so appropriate footwear is recommended. For those interested in volunteering or participating in community events, the Friends of Linn Park group holds regular sessions and meetings. Before planning your visit, it's advisable to check the official website or contact the park directly for the latest information on facilities and any scheduled events."
    },
    {
        title:"Pollok Park",
        id: '17',
        location:"2060 Pollokshaws Road, Glasgow",
        address:`<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2240.823989620263!2d-4.315090622735934!3d55.83101427311329!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4888463afdf1d965%3A0xd1ae3bcffadf1fb4!2sPollok%20Country%20Park!5e0!3m2!1sen!2suk!4v1741212639005!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
        price: "free",
        description: "Pollok Country Park, located at 2060 Pollokshaws Road, Glasgow, G43 1AT, is the city's largest green space, encompassing over 360 acres of woodlands and gardens. The park is home to the renowned Burrell Collection, which reopened after extensive refurbishment, showcasing a vast array of art and artifacts. Visitors can also explore the historic Pollok House, the ancestral residence of the Maxwell family, though it is currently closed for conservation work expected to last approximately two years from November 2023. The park offers numerous walking and cycling trails, a play park, walled gardens, and is famous for its fold of Highland cattle.",
        smallDescription: "Pollok Country Park is the city's largest green space...",
        image: "",
        type:"park",
        phone: "0141 287 5064",
        email: " info@glasgowlife.org.uk",
        tips: {
            tip1title: "By Train",
            tip1: "Pollokshaws West Station is a short walk from the park's main entrance on Pollokshaws Road.",
            tip2title: "By Bus",
            tip2: "Several bus routes service the area, with stops near the park entrances",
            tip3title: "By Car",
            tip3: "Access is via 2060 Pollokshaws Road or Lochinch Road. Parking is available at the Burrell Collection and Riverside car parks, with charges applying daily from 10 am to 6 pm (£5 for 4 hours, £10 for all day).",
        },
        details: "A free electric shuttle bus operates within the park, connecting the main entrance, Pollok House, and the Burrell Collection, running every 30 minutes from 10 am to 6:15 pm. The park encourages sustainable travel, offering cycling racks and being accessible via National Cycle Network Routes 7 and 75. Before planning your visit, it's advisable to check the official website for the latest information on facility availability and any scheduled events."
    },
    {
        title:"Botanic gardens",
        id: '18',
        location:"730 Great Western Road, Glasgow",
        address:`<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2238.0097192206485!2d-4.292850322733284!3d55.87984602313152!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x488845cbe87ec1f1%3A0x363cef30dce1cbc0!2sGlasgow%20Botanic%20Gardens!5e0!3m2!1sen!2suk!4v1741212687487!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
        price: "free",
        description: "The Glasgow Botanic Gardens, located at 730 Great Western Road, Glasgow, G12 0UE, is a renowned public garden in the city's West End. Established in 1817, the gardens span 27 acres and feature an extensive collection of plants from around the world. A highlight is the Kibble Palace, a magnificent Victorian glasshouse housing a notable collection of tree ferns and sculptures. Visitors can also explore various themed glasshouses, including the Palm House and the Main Range, each showcasing diverse plant species. The gardens offer scenic walks along the River Kelvin, expansive lawns, and a dedicated children's play area. Admission is free, and the grounds are open daily from 7:00 am until dusk. The glasshouses operate from 10:00 am to 6:00 pm during summer months and until 4:15 pm in winter.",
        smallDescription: "The Glasgow Botanic Gardens is a renowned public garden in the...",
        image: "",
        type:"park",
        phone: "0141 276 1614",
        email: " info@glasgowlife.org.uk",
        tips: {
            tip1title: "By Train",
            tip1: "Partick and Hyndland stations are about a 25-minute walk away",
            tip2title: "By Bus",
            tip2: "Multiple bus routes service Great Western Road and Byres Road, with stops close to the gardens.",
            tip3title: "By Subway",
            tip3: "The nearest station is Hillhead, approximately a 7-minute walk from the gardens.",
        },
        details: "On-street parking is available on Queen Margaret Drive adjacent to the entrance. Limited parking for blue badge holders is available within the gardens. The on-site Tea Room offers a selection of refreshments and is open daily from 10:00 am to 5:00 pm. Guided tours are available through the Friends of Glasgow Botanic Gardens, providing deeper insights into the diverse plant collections and history. Whether you're a nature enthusiast or seeking a peaceful retreat, the Glasgow Botanic Gardens provide a serene and educational experience in the heart of the city."
    },
    {
        title:"Millennium",
        id: '19',
        location:"George Square, Glasgow",
        address:`<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2239.048941171747!2d-4.253182622734276!3d55.86181727312492!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x488846a0105e2f47%3A0xc3a26f91aa71c975!2sMillennium%20Hotel%20Glasgow!5e0!3m2!1sen!2suk!4v1741212715820!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
        price: "££",
        description: "The Millennium Hotel Glasgow, located at George Square, Glasgow, G2 1DS, is a distinguished establishment in the heart of the city's vibrant center. Housed in a striking Victorian building, the hotel offers 61 en-suite bedrooms, blending historic charm with modern amenities. Guests can enjoy dining at The Brasserie on George Square, which serves contemporary Scottish cuisine with views overlooking the historic square. ",
        smallDescription: "The Millennium Hotel Glasgow is a distinguished establishment...",
        image: "",
        type:"hotels",
        phone: "+44 141 332 6711",
        email: "reservations.glasgow@millenniumhotels.com",
        tips: {
            tip1title: "By Train",
            tip1: "The hotel is adjacent to Queen Street Station and less than a 10-minute walk from Glasgow Central Station, providing excellent transport links. ",
            tip2title: "By Bus",
            tip2: "The hotel is located near the George Square that has mutiple bus stops nearby",
            tip3title: "By Air",
            tip3: "For travelers arriving by air, Glasgow International Airport is approximately 9 miles away, about a 20-minute drive.",
        },
        details: "Please note, the hotel does not offer on-site parking; however, staff can assist with nearby parking options upon request. "
    },
    {
        title:"Glasgow Argyle",
        id: '20',
        location:"27 Washington Street, Glasgow",
        address:`<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2239.2233571335846!2d-4.270456322734431!3d55.85879107312359!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4888468308d3bc53%3A0x151f8c144261e7da!2sGlasgow%20Argyle%20Hotel!5e0!3m2!1sen!2suk!4v1741212806045!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
        price: "££",
        description: "The Glasgow Argyle Hotel, BW Signature Collection by Best Western, is a 4-star establishment located at 27 Washington Street, Glasgow, G3 8AZ. Situated near the River Clyde, the hotel is within a mile of the city center, allowing guests to easily walk to attractions such as George Square, Merchant City, and Buchanan Galleries shopping center. The hotel offers 141 comfortable bedrooms, each equipped with free Wi-Fi, large flat-screen plasma TVs, and 24-hour room service. Additionally, there are 12 self-catering apartments featuring exposed brickwork and original ornate iron columns, some with mezzanine levels, making them suitable for families and business travelers. Guests can enjoy leisure facilities, including a 15-meter heated swimming pool, gym, sauna, and steam room. The on-site restaurant serves a menu prepared with seasonal ingredients, and the lounge bar offers a range of wines and beers.",
        smallDescription: "The Glasgow Argyle Hotel, BW Signature Collection by Best Western...",
        image: "",
        type:"hotels",
        phone: "+44 330 028 3407",
        email: "info@glasgowargylehotel.co.uk",
        tips: {
            tip1title: "By Train",
            tip1: "Glasgow Central Station is approximately a 10-minute walk from the hotel, providing convenient access for travelers.",
            tip2title: "By Car",
            tip2: "The hotel is just off junction 19 of the M8 motorway. On-site parking is available, but it's recommended to check availability and any associated charges in advance.",
            tip3title: "By Air",
            tip3: "Glasgow International Airport is about 8.4 miles from the hotel, roughly a 17-minute drive.",
        },
        details: "The hotel's central location makes it an excellent base for exploring Glasgow's vibrant nightlife, cultural attractions, and shopping districts. Whether attending an event at The SSE Hydro or visiting the city's museums, the Glasgow Argyle Hotel offers a comfortable and convenient stay."
    },
    {
        title:"The hilton Garden",
        id: '21',
        location:"Finnieston Quay, Glasgow",
        address: `<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1119.6360282037037!2d-4.2832057669000925!3d55.857946098174494!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x488845d81f215efd%3A0x6c7b50f63296a4c4!2sHilton%20Garden%20Inn%20Glasgow%20City%20Centre!5e0!3m2!1sen!2suk!4v1741212885903!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
        price: "££",
        description: "The Hilton Garden Inn Glasgow City Centre, located at Finnieston Quay, Glasgow, G3 8HN, is a 4-star hotel situated along the River Clyde. Adjacent to the SEC Campus, including The SSE Hydro and SEC Armadillo, the hotel offers 164 contemporary guest rooms equipped with complimentary Wi-Fi, 42-inch LCD TVs, and mini-refrigerators. Guests can enjoy dining at the on-site Recess restaurant, which features a riverside terrace for al fresco meals. Additional amenities include a 24-hour business center, fitness facilities, and on-site parking available for £10 per day. ",
        smallDescription: "The Hilton Garden Inn Glasgow City Centre, is a 4-star hotel situated...",
        image: "",
        type:"hotels",
        phone: "+44 141 240 1002",
        email: "hgiglasgow.reservations@hilton.com",
        tips: {
            tip1title: "By Train",
            tip1: "The hotel is approximately a 15-minute walk from Glasgow Central Station, offering convenient access to national rail services.",
            tip2title: "By Car",
            tip2: "Easily accessible from the M8 motorway, take junction 19 and follow signs for the SEC. On-site parking is available for £10 per day.",
            tip3title: "By Air",
            tip3: "Glasgow International Airport is about 8 miles (13 kilometers) west of the hotel, roughly a 20-minute drive.",
        },
        details: "The hotel's prime location makes it ideal for attending events at the SEC and exploring nearby attractions such as the Glasgow Science Centre and Kelvingrove Art Gallery and Museum. Public transportation options and walking paths along the River Clyde provide easy access to Glasgow's city center and West End."
    },
    {
        title:"Grosvenor",
        id: '22',
        location:"1-9 Grosvenor Terrace, Glasgow",
        address:`<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2238.119599156058!2d-4.293795522733386!3d55.877939973130744!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x488845437c264541%3A0xc01827b7fb7f6fba!2sGlasgow%20Grosvenor%20Hotel!5e0!3m2!1sen!2suk!4v1741212944203!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
        price: "££",
        description: "The Glasgow Grosvenor Hotel, located at 1-9 Grosvenor Terrace, Glasgow, G12 0TA, is a distinguished 4-star establishment nestled in the city's vibrant West End. Housed in a historic building, the hotel offers 97 contemporary rooms and suites, many boasting views of the adjacent Botanic Gardens. Guests can indulge in premium Scottish beef at the on-site Bo'Vine Meats & Wines restaurant or explore an extensive gin selection at beGIN bar. The hotel also features versatile event spaces suitable for meetings and special occasions",
        smallDescription: "The Glasgow Grosvenor Hotel,is a distinguished 4-star establishment...",
        image: "",
        type:"hotels",
        phone: "+44 141 339 8811",
        email: "reservations@gghotel.co.uk",
        tips: {
            tip1title: "By Train",
            tip1: "Partick and Hyndland railway stations are within a 20-minute walk, connecting to various parts of the city and beyond.",
            tip2title: "By Car",
            tip2: "Limited on-site parking is available on a first-come, first-served basis, with an overnight charge of £10. Alternative parking options are nearby, and the hotel is easily accessible from the M8 motorway.",
            tip3title: "By Subway",
            tip3: "The Hillhead Subway Station is a short walk from the hotel, providing easy access to Glasgow's city center and other attractions.",
        },
        details: "Whether you're visiting for business or leisure, the Glasgow Grosvenor Hotel offers a blend of historic charm and modern amenities in one of the city's most picturesque neighborhoods."
    },
    {
        title:"Malmaison",
        id: '23',
        location:"278 West George Street, Glasgow",
        address:`<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2238.9482782678406!2d-4.267417822734168!3d55.86356377312555!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4888442795495e65%3A0xd559233d628e8b2a!2sMalmaison%20Glasgow!5e0!3m2!1sen!2suk!4v1741212981994!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
        price: "££",
        description: "Malmaison Glasgow, located at 278 West George Street, Glasgow, G2 4LL, is a boutique hotel housed in a beautifully restored former Greek Orthodox Church. The hotel offers 72 stylish rooms and suites, each featuring modern amenities such as flat-screen TVs, complimentary Wi-Fi, and en-suite bathrooms. Guests can dine at the on-site Malmaison Bar & Grill, which serves a range of contemporary dishes and an extensive selection of drinks. The hotel is conveniently situated in Glasgow's city center, within walking distance of attractions like the Glasgow School of Art and the shopping district around Buchanan Street. ",
        smallDescription: "Malmaison Glasgow is a boutique hotel housed in a beautifully...",
        image: "",
        type:"hotels",
        phone: "0141 572 1000",
        email: "glasgow@malmaison.com",
        tips: {
            tip1title: "By Train",
            tip1: "Glasgow Central Station is approximately a 10-minute walk from the hotel, providing easy access for travelers arriving by rail.",
            tip2title: "By Car",
            tip2: "While the hotel does not offer on-site parking, there are public parking facilities nearby. It's advisable to check with the hotel for recommended parking options and any associated fees.",
            tip3title: "By Subway",
            tip3: "The hotel is a short walk from Sauchiehall Street, known for its vibrant nightlife and shopping. Additionally, cultural sites such as the Kelvingrove Art Gallery and Museum are easily accessible.",
        },
        details: "Please note that the hotel operates a cashless policy; all major credit and debit cards are accepted for payments."
    },

]